"""Change create_date Field

Revision ID: 8e0136c15c13
Revises: 795192afccf9
Create Date: 2025-04-12 12:55:54.166035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0136c15c13'
down_revision = '795192afccf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
